version: '3.4'

services:
  api:
    container_name: fastify-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`fastify.localhost`) && PathPrefix(`/api/v1`)'
      - 'traefik.http.routers.api.entrypoints=http'

  mongo:
    container_name: mongo
    image: 'bitnami/mongodb:4.4'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mongo.entrypoints=http'

  traefik:
    container_name: traefik-api
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker --log.level=debug --accesslog=true
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'traefik.http.routers.traefik.entrypoints=http'

volumes:
  mongodb_data:
    driver: local
